import {renderStudio, followJob, studioConnection} from './studio.js';
const $ = s => document.querySelector(s);
const escape = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels = {queued:'Queued',running:'In progress',retry:'Waiting to retry',verifying:'Confirming publication',needs_attention:'Needs attention',done:'Verified live',cancelled:'Cancelled'};
let state, refreshRequest=null, lastTopics=0;
const time = n => new Date(typeof n === 'number' ? n*1000 : n).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const pill = (s,label) => `<span class="pill ${s==='needs_attention'?'bad':s==='verifying'||s==='retry'?'warn':''}">${escape(label||labels[s]||s)}</span>`;
function toast(text){$('#toast').textContent=text;}
function route(){const view=['today','topics','history'].includes(location.hash.slice(1))?location.hash.slice(1):'today';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('nav a').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('#heading').textContent={today:'Good stories. On schedule.',topics:'A little curiosity goes a long way.',history:'Every episode, accounted for.'}[view];if(view==='topics')topics();}
async function action(body,button){if(!state){toast('Wait for Tower to connect.');return;}if(button)button.disabled=true;try{const r=await fetch('../api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,csrf:state.csrf})});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');toast(data.message);if(body.action==='enqueue'&&data.id)followJob(data.id);if(refreshRequest)await refreshRequest;await refresh();if(body.action==='enqueue')$('#studio').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});return data;}catch(e){toast(e.message);return false;}finally{if(button)button.disabled=false;}}
function render(){
 renderStudio(state);
 const jobs=state.jobs, active=jobs.filter(j=>['queued','running','retry','verifying'].includes(j.status)), attention=jobs.filter(j=>j.status==='needs_attention');
 const stamp=state.status.ts, stale=!stamp||Date.now()-Date.parse(stamp)>11*60000;
 $('#connection').textContent=stale?'Supervisor data is stale':'Connected to Tower';$('#connection').className='pill'+(stale?' warn':'');
 const failedChecks=(state.preflight?.checks||[]).filter(c=>!c.ok);$('#active-count').textContent=active.length;$('#attention-count').textContent=attention.length+failedChecks.length;$('#attention-detail').textContent=failedChecks.length?'Preflight: '+failedChecks.map(c=>c.name).join(', '):'Only issues requiring a decision';
 const rules=state.status.rules||[];const daily=rules.find(r=>r.id==='briefing_uploaded');const live=rules.find(r=>r.id?.startsWith('live:gk_daily_')&&r.state==='ok');
 $('#delivery').textContent=stale?'Status needs a refresh':live?'Morning edition is live':daily?.state==='ok'?'Confirming publication':'Morning edition pending';
 $('#delivery-detail').textContent=live?'Public feed confirmation recorded.':daily?.detail||'Target: verified live by 6:35 AM CT';
 const problems=rules.filter(r=>r.state==='firing'&&r.severity!=='info');
 $('#health-title').textContent=stale?'Waiting for fresh evidence':problems.length?'Some checks need attention':'The essentials look good';
 const health=rules.filter(r=>['volumes_mounted','drive_mounted','session_fresh','disk_space','launchd_loaded'].includes(r.id));
 $('#health').innerHTML=health.map(r=>`<div class="health-row"><span>${escape(r.label)}</span><span class="${r.state==='ok'?'ok':'warning'}">${r.state==='ok'?'✓ Ready':escape(r.state)}</span></div>`).join('');
 $('#last-check').textContent=stamp?'Supervisor checked '+time(stamp):'No supervisor snapshot yet';
 $('#jobs').innerHTML=jobs.slice(0,20).map(j=>`<article class="job"><div><h3>${escape(j.title)}</h3>${pill(j.status,j.status==='done'&&!j.verified?'Completed · historical record':null)}<p>${escape(j.status==='done'?'Completed':j.stage)} · Updated ${time(j.updated)}</p>${j.error?`<p class="error">${escape(j.error)}</p>`:''}</div><div class="job-buttons">${['special','script'].includes(j.kind)?`<button class="subtle" data-follow="${j.id}">Follow</button>`:''}<button class="subtle" data-detail="${j.id}">Details</button>${j.status==='needs_attention'?`<button data-job="${j.id}" data-action="${j.episode?'reconcile':'retry'}">${j.episode?'Check publication':'Retry'}</button>`:''}${['queued','retry'].includes(j.status)?`<button class="subtle" data-job="${j.id}" data-action="cancel">Cancel</button>`:''}</div></article>`).join('')||'<div class="empty">Nothing in the queue. Your next story starts above.</div>';
 $('#episodes').innerHTML=state.episodes.map(ep=>`<article class="job"><div><h3>${escape(ep.title)}</h3><p>Upload recorded ${time(ep.uploaded.replace(' UNVERIFIED',''))}${ep.late_upload?' · After the 6:35 AM target':''}</p></div>${pill(ep.delivery?.state==='verified_live'?'done':'verifying',ep.delivery?.state==='verified_live'?'Verified live':'Upload recorded · not verified here')}</article>`).join('')||'<p class="empty">No recent episode records.</p>';
}
async function refresh(){
 if(refreshRequest)return refreshRequest;
 refreshRequest=(async()=>{try{const r=await fetch('../api/state',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Tower is temporarily unavailable');state=await r.json();render();studioConnection(true);}catch(e){$('#connection').textContent='Connection interrupted';$('#connection').className='pill bad';studioConnection(false);}})();
 try{return await refreshRequest;}finally{refreshRequest=null;}
}
async function topics(){if(Date.now()-lastTopics<10000)return;lastTopics=Date.now();try{const r=await fetch('../api/topics');const data=await r.json();$('#topics-error').textContent=data.error||'';$('#topic-list').replaceChildren();(data.topics||[]).forEach((topic,i)=>{const row=document.createElement('div');row.className='topic-row';row.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><p>${escape(topic)}</p><div class="topic-controls"><button class="subtle use">Use ↗</button><button class="subtle edit">Edit</button><button class="subtle delete">Delete</button><button class="subtle up" aria-label="Move topic up" ${i===0?'disabled':''}>↑</button></div>`;row.querySelector('.use').onclick=()=>{$('#topic').value=topic;localStorage.setItem('gk-topic-draft',topic);location.hash='today';$('#topic').focus();};row.querySelector('.edit').onclick=()=>{const paragraph=row.querySelector('p');const input=document.createElement('textarea');input.value=topic;paragraph.replaceWith(input);const controls=row.querySelector('.topic-controls');controls.innerHTML='<button class="save">Save</button>';controls.querySelector('button').onclick=async e=>{if(await action({action:'edit_topic',old:topic,topic:input.value},e.target)){lastTopics=0;setTimeout(topics,1500);}};input.focus();};row.querySelector('.delete').onclick=async e=>{if(!confirm(`Delete this topic from the queue?\n\n${topic}`))return;if(await action({action:'delete_topic',old:topic},e.target)){row.remove();lastTopics=0;setTimeout(topics,1500);}};row.querySelector('.up').onclick=async e=>{if(await action({action:'swap_topic',old:topic,swap:data.topics[i-1]},e.target)){lastTopics=0;setTimeout(topics,1500);}};$('#topic-list').append(row);});}catch(e){$('#topics-error').textContent='Topic queue is temporarily unavailable.';}}
$('#request').onsubmit=async e=>{e.preventDefault();const topic=$('#topic').value.trim();if(await action({action:'enqueue',topic},e.submitter)){$('#topic').value='';localStorage.removeItem('gk-topic-draft');}};
$('#topic').value=localStorage.getItem('gk-topic-draft')||'';$('#topic').oninput=e=>localStorage.setItem('gk-topic-draft',e.target.value);
$('#daily').onclick=e=>action({action:'daily'},e.target);
$('#jobs').onclick=e=>{const follow=e.target.closest('[data-follow]');if(follow){followJob(follow.dataset.follow);$('#studio').scrollIntoView({block:'center'});return;}const jobButton=e.target.closest('[data-job]');if(jobButton){action({action:jobButton.dataset.action,id:jobButton.dataset.job},jobButton);return;}const detail=e.target.closest('[data-detail]');if(!detail)return;showJobDetails(detail.dataset.detail);};
function showJobDetails(id){const j=state.jobs.find(j=>j.id===id);if(!j)return;$('#detail-title').textContent=j.title;const events=state.events.filter(ev=>ev.job_id===j.id).reverse();$('#detail-body').innerHTML=`${pill(j.status,j.status==='done'&&!j.verified?'Completed · historical record':null)}<p>Created ${time(j.created)} · ${j.attempts} attempt(s)</p>${j.error?`<p>${escape(j.error)}</p>`:''}${j.last_error?`<details><summary>Diagnostic detail</summary><pre>${escape(j.last_error)}</pre></details>`:''}${events.map(ev=>`<div class="event"><small>${time(ev.ts)}</small>${escape(ev.detail||ev.kind)}</div>`).join('')||'<p>No detailed events were recorded for this older request.</p>'}`;$('#detail').showModal();}

$('#studio').onclick=e=>{const button=e.target.closest('[data-studio-action]');if(button){action({action:button.dataset.studioAction,id:button.dataset.id},button);return;}const detail=e.target.closest('[data-studio-detail]');if(detail)showJobDetails(detail.dataset.studioDetail);};
$('#detail .close').onclick=()=>$('#detail').close();window.addEventListener('hashchange',route);
$('#date').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}).toUpperCase();route();refresh();setInterval(()=>{refresh();if(location.hash==='#topics')topics();},5000);

$('#add-topic').onsubmit=async e=>{e.preventDefault();if(await action({action:'add_topic',topic:$('#new-topic').value},e.submitter)){$('#new-topic').value='';lastTopics=0;setTimeout(topics,1500);}};
